### ISSUE TITLE
Bad request: Model requires a Pro subscription

### ISSUE THREAD

**Issue by zhuxiaosheng** [philschmid/easyllm#14]
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_errors.py](https://localhost:8080/#) in hf_raise_for_status(response, endpoint_name)
    260     try:
--> 261         response.raise_for_status()
    262     except HTTPError as e:

7 frames
HTTPError: 400 Client Error: Bad Request for url: https://api-inference.huggingface.co/models/meta-llama/Llama-2-70b-chat-hf

The above exception was the direct cause of the following exception:

BadRequestError                           Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_errors.py](https://localhost:8080/#) in hf_raise_for_status(response, endpoint_name)
    297                 f"\n\nBad request for {endpoint_name} endpoint:" if endpoint_name is not None else "\n\nBad request:"
    298             )
--> 299             raise BadRequestError(message, response=response) from e
    300 
    301         # Convert `HTTPError` into a `HfHubHTTPError` to display request information

BadRequestError:  (Request ID: dzqk3ZqfFF4wh7pIc4rC7)

Bad request:
Model requires a Pro subscription

**Comment by philschmid** [comment]
Yes thats correct to use `meta-llama/Llama-2-70b-chat-hf` you need a pro subscription on HF: https://huggingface.co/subscribe/pro

But you can use it with other models as well.

**Comment by pharringtonp19** [comment]
@philschmid Is there a per token cost like with openai? Or is the pro subscription the only cost?

**Comment by philschmid** [comment]
Currently, Llama 2 70B is available once you have a pro subscription there is no token price. I am not sure though what is planned for the future.

**Comment by WenchenLi** [comment]
> 

i tried, meta-llama/Llama-2-7b-chat-hf, meta-llama/Llama-2-7b-chat, etc. All of them mentioned need pro subscription. 
any dependencies that you use only pro user have ?

```
lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 299, in hf_raise_for_status
    raise BadRequestError(message, response=response) from e
huggingface_hub.utils._errors.BadRequestError:  (Request ID: TExJwHr1akynuhQQzMtA3)

Bad request:
Model requires a Pro subscription
```

**Comment by WenchenLi** [comment]
> > 
> 
> i tried, meta-llama/Llama-2-7b-chat-hf, meta-llama/Llama-2-7b-chat, etc. All of them mentioned need pro subscription. any dependencies that you use only pro user have ?
> 
> ```
> lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 299, in hf_raise_for_status
>     raise BadRequestError(message, response=response) from e
> huggingface_hub.utils._errors.BadRequestError:  (Request ID: TExJwHr1akynuhQQzMtA3)
> 
> Bad request:
> Model requires a Pro subscription
> ```

cause i use hf official have no pro requirement for the same model. 
```
from transformers import AutoTokenizer
import transformers
import torch

model = "meta-llama/Llama-2-7b-chat-hf"
tokenizer = AutoTokenizer.from_pretrained(model)
pipeline = transformers.pipeline(
    "text-generation",
    model=model,
    torch_dtype=torch.float16,
    device_map="auto",
)

sequences = pipeline(
    'I liked "Breaking Bad" and "Band of Brothers". Do you have any recommendations of other shows I might like?\n',
    do_sample=True,
    top_k=10,
    num_return_sequences=1,
    eos_token_id=tokenizer.eos_token_id,
    max_length=200,
)
for seq in sequences:
    print(f"Result: {seq['generated_text']}")

```
