### ISSUE TITLE
Move makefile to hatch scripts

### ISSUE THREAD

**Issue by chainyo** [philschmid/easyllm#19]
Hi @philschmid 

I'm discovering `hatch` being a `poetry` or `setuptools` user.

Could it be worth it to move all the Makefile scripts to the hatch scripts systems to make them use automatically the optional dependencies and also move the optional-dependencies under a `[tool.hatch.envs.NAME]`?

Like [this example from the hatch documentation](https://hatch.pypa.io/latest/config/environment/overview/#scripts).

Wdyt?

**Comment by philschmid** [comment]
I am not using `hatch` for the environment locally. I use conda and just do `pip install -e .`. But hatch had some nice benefits for builds, and the single `pyproject.toml` was interesting to me. 
So Not sure whats better.

**Comment by chainyo** [comment]
Ok, I saw the hatch tooling suite in the pyproject.toml which was misleading :)

**Comment by philschmid** [comment]
Yeah currently i only use it for building
