### ISSUE TITLE
Integration with self hosted models through TGI

### ISSUE THREAD

**Issue by SupreethRao99** [philschmid/easyllm#2]
Hello,

It would be great if easyLLM could integrate with models that are self hosted through huggingface text generation inference. This could be built the same way the openAI client deals with models hosted through AzureOpenAI (by providing a base URL, deployment-name, API version etc). 

Would be happy to contribute and build this feature out.

Thank You!

**Comment by philschmid** [comment]
Hello @SupreethRao99,

That should already be supported. You can change the URL in the same way by setting `huggingface.api_base = "https:/"`. See https://philschmid.github.io/easyllm/clients/huggingface/#changing-url

**Comment by philschmid** [comment]
See for example: https://philschmid.github.io/easyllm/examples/inference-endpoints-example/
