### ISSUE TITLE
Local inference of TGI

### ISSUE THREAD

**Issue by bacoco** [philschmid/easyllm#21]
Hello,

I made a local docker container using TGI. I use TheBloke/Llama-2-13B-fp16 model

I define:
from easyllm.clients import huggingface
huggingface.prompt_builder = "llama2"
huggingface.api_base = "http://localhost:8080"

and use simple completion (same for chat):

response = huggingface.Completion.create(
    prompt="What is the meaning of life?",
    temperature=0.9,
    top_p=0.6,
    max_tokens=1024,
)
response:

But response look like :
{'id': 'hf-FJZ72HMlsF',
 'object': 'text.completion',
 'created': 1691331574,
 'choices': [{'index': 0,
   'text': '\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST] What is the meaning of life? [/INST]\n[INST]',
   'finish_reason': 'length'}],
 'usage': {'prompt_tokens': 11,
  'completion_tokens': 1024,
  'total_tokens': 1035}}
  

Do you have any idea please ?
Thanks

Ps: http://localhost:8080/info give
{
  "model_id": "TheBloke/Llama-2-13B-fp16",
  "model_sha": "b2e65e8ad4bb35e5abaee0170ebd5fc2134a50bb",
  "model_dtype": "torch.float16",
  "model_device_type": "cuda",
  "model_pipeline_tag": "text-generation",
  "max_concurrent_requests": 128,
  "max_best_of": 2,
  "max_stop_sequences": 4,
  "max_input_length": 1024,
  "max_total_tokens": 2048,
  "waiting_served_ratio": 1.2,
  "max_batch_total_tokens": 7984,
  "max_waiting_tokens": 20,
  "validation_workers": 2,
  "version": "1.0.0",
  "sha": "3ef5ffbc6400370ff2e1546550a6bad3ac61b079",
  "docker_label": "sha-3ef5ffb"
}

**Comment by bacoco** [comment]
I try :
from typing import List, Union
from easyllm.prompt_utils import llama2
from easyllm.schema.base import ChatMessage

llama2_stop_sequences = ["</s>"]
llama2.build_llama2_prompt("What is the meaning of life?")

and get 
'<s>[INST] What is the meaning of life? [/INST]'

There is not </s> at the end

**Comment by bacoco** [comment]
I found the solution. It didn't work with standard model only chat one's.
It work if i use :**TheBloke/Llama-2-13B-chat**-GPTQ


{
  "model_id": "TheBloke/Llama-2-13B-chat-GPTQ",
  "model_sha": "01bfd1c28783056bf8817b6d487f0efbbabe1804",
  "model_dtype": "torch.float16",
  "model_device_type": "cuda",
  "model_pipeline_tag": "text-generation",
  "max_concurrent_requests": 128,
  "max_best_of": 2,
  "max_stop_sequences": 4,
  "max_input_length": 1024,
  "max_total_tokens": 2048,
  "waiting_served_ratio": 1.2,
  "max_batch_total_tokens": 17008,
  "max_waiting_tokens": 20,
  "validation_workers": 2,
  "version": "1.0.0",
  "sha": "3ef5ffbc6400370ff2e1546550a6bad3ac61b079",
  "docker_label": "sha-3ef5ffb"
}

**Comment by philschmid** [comment]
I have two examples here: https://github.com/philschmid/deep-learning-pytorch-huggingface/tree/main/inference#text-generation-infernece-gptq
