### ISSUE TITLE
Chat completion format for empty system content.

### ISSUE THREAD

**Issue by viniciusarruda** [philschmid/easyllm#6]
Hi, 

I was looking the meta [implementation](https://github.com/facebookresearch/llama/blob/main/llama/generation.py#L212) for the chat completion, and it seems that there is no way to get an empty system. 
However, with `easyllm` is possible to use it with empty system input. 
Is it expected to work correctly? I mean, LLaMA v2 was trained with empty system?

**Comment by philschmid** [comment]
It's not completely clear how the training data looked. But you can definitely leave out the system prompt, especially for single-turn instructions.

**Comment by viniciusarruda** [comment]
The stuff I tested, even using a badly formatted chat completion structure, LLaMA v2 could produce good results (when compared to the correct format). However, I'm looking for the ideal output, i.e., using the correct format used to train.
If you know something about using chat completion without the system prompt, please let me know. I didn't found anything about it.

**Comment by philschmid** [comment]
If you fine-tuning dataset is not having a system prompt for your instructions then you should omit it.
